name: Deploy to EC2

on:
  push:
    branches: 
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get EC2 Public IPs
        id: get-ips
        run: |
          INSTANCE_IPS=$(aws ec2 describe-instances \
            --filters "Name=tag:Environment,Values=staging" "Name=instance-state-name,Values=running" \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text | tr '\n' ',' | sed 's/,$//')

          if [ -z "$INSTANCE_IPS" ]; then
            echo "No running instances found with specified tags"
            exit 1
          fi

          echo "instance_ips=${INSTANCE_IPS}" >> "$GITHUB_OUTPUT"

      - name: SSH into instances and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key

          # Read IPs from output
          INSTANCE_IPS="${{ steps.get-ips.outputs.instance_ips }}"

          # For each instance, deploy
          for IP in $(echo $INSTANCE_IPS | tr ',' ' '); do
            echo "Deploying to $IP..."

            ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@$IP << 'EOF'
              set -e  # Exit immediately if a command exits with a non-zero status
              
              cd /home/ubuntu/django-app-terraform
              git pull origin staging
              
              # Stop and remove existing container
              docker stop app || true
              docker rm app || true
              docker build -t django-app-img .

              # Run new container
              docker run -d \
                --name app \
                -p 8000:8000 \
                django-app-img
            EOF
          done
