name: Build and push docker image to EKS
on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]


    # paths: 
    #   - "kubernetes/*"
    #   - ".github/workflows/deploy-eks.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' 
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: django
        IMAGE_TAG: latest
      run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    

    - name: Update kube config
      run: aws eks update-kubeconfig --name django-app-cluster

    - name: Deploy django-app helm chart to EKS
      run: |
        helm uninstall django-app -n helm
        cd kubernetes/helm-app
        helm install django-app . -n helm